---
steps:
#Deploy de notre image
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args: ['apply', '-f', './manifest/10-shipping.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-a'
  - 'CLOUDSDK_COMPUTE_REGION=northamerica-northeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-pfr-main'
